version: '{build}'
image: Visual Studio 2019
configuration: Release
platform: Any CPU
before_build:
- cmd: appveyor-retry nuget restore
build:
  project: NLyric.sln
  verbosity: normal
after_build:
- cmd: dotnet publish NLyric\NLyric.csproj -c Release -f netcoreapp2.1
artifacts:
- path: bin\Release\net472
  name: NLyric-net472
- path: bin\Release\netcoreapp2.1\publish
  name: NLyric-netcoreapp2.1
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: NLyric
  auth_token:
    secure: +8UJ1C312inNq+80I8WST34vPMrCylnmTx+9rmuIh1qnsArA5x2b8yc+kcwkXmQC
  on:
    APPVEYOR_REPO_TAG: true